url: http://berg-catalani.com/
baseurl: ''

# Site settings
title: "#ashnerin2019"
email: wedding@berg-catalani.com
description: "Ashley Berg and Erin Catalani are tying the knot on July 20, 2019"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3dbbf0
  secondary: 2f90b9  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/abrg

# Build settings
markdown: kramdown
permalink: pretty
